### PR TITLE
Rich text editor

### PR DESCRIPTION
**Pull request by Vadis00**
`<tasque-rich-text-editor></tasque-rich-text-editor>
`

### CODE REVIEW

**Comment by Anatolii-Ivanov** [comment]
What is the purpose of this task?

**Comment by Vadis00** [comment]
needed for https://trello.com/c/mkUVGZ9p/52-task-creation-modal
https://trello.com/1/cards/62f2c556d39d823458492066/attachments/62f798787d00fc1ecc477217/previews/62f798797d00fc1ecc477276/download/Create_issue_figma.png

**Comment by Anatolii-Ivanov** [comment]
Let's use library editor and won't write a custom one...
Just add the existing one https://morioh.com/p/3dc9c5fd3dec

**Comment by Vadis00** [comment]
> Let's use library editor and won't write a custom one... Just add the existing one https://morioh.com/p/3dc9c5fd3dec

oh well

**Pull request closed without merging**
