### PR TITLE
Login page improvements

### PR DESCRIPTION
**Pull request by ihor-il**
## Login page improvements proposal
1.  Cursor on logo is pointer (is it intended?)
2. Cursor on buttons is not pointer
3. Icons for Google and GH auth instead of a text
4. Replace `Forget password` with `Restore password` or `Forgot password?`

### CODE REVIEW

**Comment by ihor-il** [comment]
`Restore password` button and `Password` label have the same look. Maybe more gray-ish color for the button?

**Review by ismv — COMMENTED** [review]
1) it might not be needed on the login page, but usually clicking the logo should lead user to the main page
2) if we have button reaction on hover then no, both cursor change and highlighting is redundant
3) probably fine but we should see how those icons align with page color scheme
4) `Forgot password?` I like this alternative

**Comment by ihor-il** [comment]
3. We could use outline icons from FontAwesome like [this one](https://fontawesome.com/icons/google?s=brands) for Google and [this one](https://fontawesome.com/icons/github?s=brands) for GH and make them any color we need

**Comment by ihor-il** [comment]
1. Its not just logo but whole background area. imo it would be better if only the logo could be clicked on

зображення

**Comment by ihor-il** [comment]
What do you think? 

зображення

**Comment by ihor-il** [comment]
Final result

image

image (2)

**Review by ismv — APPROVED** [review]
lgtm

**Review by Setup1337 — APPROVED** [review]

**Pull request merged**
